### ISSUE TITLE
Instance switcheroo involving base-compat, semigroupoids, and bifunctors

### ISSUE THREAD

**Issue by RyanGlScott** [sol/base-compat#15]
I've been thinking of a couple of ways to improve `base-compat`, and unfortunately, two of my ideas are likely to clash at some point:

* I feel that `base-compat` should be the canonical source for the orphan `Foldable`/`Traversable` instances for `Either a b` and `(a, b)`. Unfortunately, at the moment another package ([`semigroupoids`](http://hackage.haskell.org/package/semigroupoids)) also defines these orphan instances in its [`Data.Traversable.Instances`](http://hackage.haskell.org/package/semigroupoids-4.3/docs/Data-Traversable-Instances.html) module, so `semigroupoids` should probably be changed to import those orphan instances from `base-compat`.
* At some point, we should create a `Data.Bifunctor.Compat` module that exports the `Data.Bifunctor` module from the [`bifunctors`](http://hackage.haskell.org/package/bifunctors)  library with old versions of `base`.

However, doing both is impossible at the moment, since `semigroupoids` is a dependency of `bifunctors`! Implementing both suggestions would create a `base-compat` -> `semigroupoids` -> `bifunctors` -> `base-compat` dependency cycle.

There is a fix for this problem, but it would be somewhat involved. In addition to doing both of the above things, the instances in `bifunctors` that use typeclasses from `semigroupoids` would need to be moved to the other package (so that `semigroupoids` depends on `bifunctors`, and not the other way around).

@ekmett: Since you're the maintainer of `bifunctors` and `semigroupoids`, would you have any objections to this plan?

**Comment by sol** [comment]
As we define orphan instances it's in the nature of the package that there can be only one `base-compat`, otherwise things don't compose anymore.  For that reason I think he most important design goal for `base-compat` is to reduce potential for controversy, so that hopefully everybody can accept it and depend on it.

Specifically I would do the following things:

1. Only depend on `base` (transitive dependencies of `base`, like `ghc-prim` are fine too)
1. Only define orphan instances that are not on Hackage yet
1. When there is a conflict between "controversial and more complete" and "not controversial and less complete", go with the later

(related to (1) we have #6 and I closed #8 as won't fix)

That would mean that we remove the instances for `Either a b` and `(a, b)` again, at least for now.  We can add them again if @ekmett agrees to remove them from `semigroupoids` (and optionally depend on `base-compat`).

@RyanGlScott Does this make sense?   What do you think?

**Comment by RyanGlScott** [comment]
I have no problem with guideline (1), as the alternative is to just have one's libraries depend on both `base-compat` and `bifunctors`. This dodges the dependency cycle issue completely. (Would guideline (1) imply that we should remove `setenv` as a dependency eventually?)

However, I would like to try and make a pull request to `semigroupoids` and see if @ekmett is willing to depend on `base-compat` before removing the orphan `Either`/`(,)` instances from `base-compat`. If that goes through, then we wouldn't need to remove the orphan instances (which I view as a good thing, since I think it makes more sense for them to live in `base-compat` than `semigroupoids`).

**Comment by RyanGlScott** [comment]
I've opened two pull requests for [`semigroupoids`](https://github.com/ekmett/semigroupoids/pull/27) and [`lens`](https://github.com/ekmett/lens/pull/539) (which I discovered also exports the same orphan instances).

**Comment by RyanGlScott** [comment]
The consensus seems to be that we should move the orphan instances to a yet-to-be-created `base-orphans` package, so this issue should be moved there. I can think of some other packages that already defined `base`-related orphan instances (e.g., `transformers` defines orphan `Alternative`/`Monad`/`MonadFix` instances for `Either` on `base-4.2.0.0` and earlier), so we can address those as well.
